import { createPinia } from 'pinia'
import { setActivePinia } from 'pinia'
import { createI18n } from 'vue-i18n'
import { config } from '@vue/test-utils'

const i18n = createI18n({
  legacy: false,
  locale: 'zh-CN',
  fallbackLocale: 'zh-CN',
  messages: {
    'zh-CN': {
      common: {
        save: '保存',
        cancel: '取消',
        delete: '删除',
        confirm: '确认',
        add: '添加',
        edit: '编辑',
        close: '关闭',
        search: '搜索',
        settings: '设置',
        back: '返回'
      },
      nav: {
        home: '待办',
        completed: '已完成',
        calendar: '日历',
        stats: '统计',
        pomodoro: '番茄钟',
        settings: '设置',
        myDay: '我的一天',
        tomorrow: '明天',
        nextWeek: '下周',
        important: '重要',
        planned: '已计划',
        allTasks: '全部任务',
        categories: '分类',
        search: '搜索任务...',
        searchResults: '搜索结果',
        categoryTasks: '分类任务',
        tasks: '任务'
      },
      task: {
        newTask: '新建任务',
        editTask: '编辑任务',
        taskTitle: '任务标题',
        taskDetails: '任务详情',
        date: '日期',
        time: '时间',
        category: '分类',
        priority: '优先级',
        reminder: '提醒',
        repeat: '重复',
        subTasks: '子任务',
        completed: '已完成',
        overdue: '已逾期',
        noTasks: '暂无任务',
        addTaskPlaceholder: '添加任务，试试「明天下午3点 开会 重要」',
        markAllCompleted: '全部完成',
        smartDetected: '识别到：',
        clearCompleted: '清除已完成任务',
        addSubtaskPlaceholder: '添加子任务...',
        deleteTaskConfirm: '确定要删除这个任务吗？',
        notes: '备注',
        noTime: '无时间',
        subtasks: '子任务 {done}/{total}',
        today: '今天',
        yesterday: '昨天',
        tomorrowLabel: '明天',
        noDate: '无截止日期',
        titlePlaceholder: '输入任务标题...',
        selectCategory: '选择分类',
        dateTime: '日期与时间',
        selectDate: '选择日期',
        selectTime: '选择时间',
        voiceInput: '语音输入',
        stopRecording: '停止录音',
        selectColor: '选择颜色',
        addTag: '添加标签',
        repeatFrequency: '重复频率',
        repeatInterval: '重复间隔',
        endRepeat: '结束重复',
        noRepeat: '不重复',
        daily: '每天',
        weekly: '每周',
        markComplete: '标记为已完成',
        markIncomplete: '标记为未完成',
        editTaskAria: '编辑任务: {title}',
        startFocus: '开始专注',
        deleteTask: '删除任务',
        deletedMessage: '任务已删除',
        undo: '撤销',
        monday: '周一',
        tuesday: '周二',
        wednesday: '周三',
        thursday: '周四',
        friday: '周五',
        saturday: '周六',
        sunday: '周日',
        addSubTask: '添加子任务'
      },
      categories: {
        work: '工作',
        personal: '个人',
        study: '学习',
        shopping: '购物',
        health: '健康',
        other: '其他',
        manage: '分类管理',
        addNew: '添加新分类',
        name: '分类名称',
        color: '选择颜色',
        deleteConfirm: '确认删除分类？',
        batchDelete: '批量删除',
        editCategory: '编辑分类',
        deleteCategory: '删除分类'
      },
      settings: {
        title: '设置',
        subtitle: '个性化你的任务体验',
        appearance: '外观',
        theme: '主题模式',
        themeDesc: '选择浅色、深色或跟随系统',
        light: '浅色',
        dark: '深色',
        system: '系统',
        fontSize: '字体大小',
        small: '小',
        medium: '中',
        large: '大',
        pomodoro: '番茄钟',
        workDuration: '专注时长',
        shortBreak: '短休息时长',
        longBreak: '长休息时长',
        notifications: '通知',
        data: '数据',
        exportData: '导出数据',
        importData: '导入数据',
        resetData: '恢复默认数据',
        clearData: '清除所有数据',
        about: '关于',
        version: '版本',
        shortcuts: '快捷键',
        language: '语言',
        languageDesc: '选择界面显示语言',
        chinese: '简体中文',
        english: 'English',
        japanese: '日本語',
        testNotification: '测试通知',
        clearAllDataConfirm: '清除所有数据',
        clearAllDataDesc: '此操作将删除所有任务和设置，无法恢复。',
        confirmClear: '确认清除',
        resetDataConfirm: '恢复默认数据',
        resetDataDesc: '这将清除当前数据并恢复示例任务。',
        confirmReset: '确认恢复',
        dataCleared: '数据已清除',
        resetDataSuccess: '已恢复默认数据',
        glassEffect: '毛玻璃效果',
        sidebarCollapsed: '侧边栏折叠',
        themeColor: '主题色',
        defaultReminderTime: '默认提醒时间',
        doNotDisturb: '免打扰模式',
        autoStart: '开机自启',
        closeToQuit: '关闭窗口即退出',
        longBreakInterval: '长休息间隔'
      },
      pomodoro: {
        work: '专注',
        shortBreak: '短休息',
        longBreak: '长休息',
        start: '开始',
        pause: '暂停',
        reset: '重置',
        sessions: '番茄数'
      },
      stats: {
        title: '统计',
        totalTasks: '总任务数',
        completedTasks: '已完成',
        overdueTasks: '已逾期',
        completionRate: '完成率',
        thisWeek: '本周',
        thisMonth: '本月'
      },
      empty: {
        title: '还没有任务',
        subtitle: '添加你的第一个任务，开始高效的一天',
        action: '添加任务',
        completed: '还没有已完成的任务',
        completedSubtitle: '完成任务后会显示在这里'
      },
      shortcuts: {
        newTask: '新建任务',
        search: '搜索',
        complete: '完成任务',
        important: '标记重要',
        openSettings: '打开设置',
        togglePomodoro: '番茄钟开关'
      },
      debug: {
        title: '调试工具',
        appearance: '外观',
        devTools: '开发工具',
        openDevTools: '打开开发者工具',
        notification: '通知测试',
        sendTest: '发送测试通知',
        viewToast: '查看右下角弹窗',
        systemInfo: '系统信息',
        platform: '平台',
        restoreDefault: '恢复系统默认',
        errorMonitor: '错误监控',
        totalRecords: '条记录',
        refresh: '刷新',
        clear: '清空',
        mockError: '模拟错误',
        noErrors: '暂无错误',
        total: '总数',
        last24h: '24h',
        types: '类型'
      },
      date: {
        weekdays: ['周日', '周一', '周二', '周三', '周四', '周五', '周六']
      },
      sidebar: {
        collapse: '收起',
        collapseSidebar: '收起侧边栏',
        expand: '展开',
        expandSidebar: '展开侧边栏'
      }
    }
  }
})

config.global.plugins.push(i18n)

beforeEach(() => {
  setActivePinia(createPinia())
})
